using System;
using System.Threading;
using System.Threading.Tasks;
using Windows.Graphics.Imaging;
using Windows.Storage;
using Windows.Storage.Streams;

namespace Fastcull.Services
{
    /// <summary>
    /// Decodes JPEG/PNG thumbnails via WIC (Windows.Graphics.Imaging), per PRD 3.2's
    /// "generated by downscaled decode" tier. Returns a plain SoftwareBitmap - no XAML
    /// types touched here, so this never needs the UI thread. Callers marshal the result
    /// onto the UI thread themselves to wrap it as a bindable ImageSource.
    /// </summary>
    public static class ThumbnailService
    {
        private const uint ThumbnailLongEdge = 160;

        public static async Task<SoftwareBitmap?> DecodeThumbnailAsync(string filePath, CancellationToken cancellationToken = default)
        {
            try
            {
                using var stream = await FileRandomAccessStream.OpenAsync(filePath, FileAccessMode.Read)
                    .AsTask(cancellationToken).ConfigureAwait(false);
                var decoder = await BitmapDecoder.CreateAsync(stream).AsTask(cancellationToken).ConfigureAwait(false);

                var scale = Math.Min(1.0, ThumbnailLongEdge / (double)Math.Max(decoder.PixelWidth, decoder.PixelHeight));
                var transform = new BitmapTransform
                {
                    ScaledWidth = (uint)Math.Max(1, Math.Round(decoder.PixelWidth * scale)),
                    ScaledHeight = (uint)Math.Max(1, Math.Round(decoder.PixelHeight * scale)),
                    InterpolationMode = BitmapInterpolationMode.Fant,
                };

                return await decoder.GetSoftwareBitmapAsync(
                    BitmapPixelFormat.Bgra8,
                    BitmapAlphaMode.Premultiplied,
                    transform,
                    ExifOrientationMode.RespectExifOrientation,
                    ColorManagementMode.DoNotColorManage).AsTask(cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}
